### ISSUE TITLE
Search bar captures '/' key presses even when focus is in the text editor

### ISSUE THREAD

**Issue by tpakeman** [looker-open-source/extension-api-explorer#1]
`/` is the shortcut to start searching, but this is making it impossible to type literal `/` characters in the text editor on the right hand side (behind the 'Run it' button)

This is a problem when you are trying to use the  `create_sso_embed_url` endpoint as you need to be able to type a URL path as part of the body of the request!

The `/` shortcut should only capture when the user is not editing in the text editor

**Comment by josephaxisa** [comment]
Thanks for reporting this @tpakeman. The latest version addresses this. Also in the future it's best to file any bugs you encounter in https://github.com/looker-open-source/sdk-codegen/
